version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: npm test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: heroku stack:set --app $HEROKU_APP_NAME container
      - heroku/deploy-via-git

workflows:
  default:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
